### ISSUE TITLE
readme? how to use it

### ISSUE THREAD

**Issue by MoozenSoft** [Deadleg/idea-openresty-lua-support#1]

**Comment by Deadleg** [comment]
Sorry will get it done later today.

If you have the lua plugin installed, it should give auto-completion with anything starting with 'ngx'. If you don't have the lua plugin installed, it will just break.

E.g. if you start typing `ngx.req.` you should see `get_headers`, `set_header` etc.

**Comment by Deadleg** [comment]
If you have any more questions feel free to open another issue.
