### ISSUE TITLE
Out of Date

### ISSUE THREAD

**Issue by splitice** [Deadleg/idea-openresty-lua-support#2]
Unfortunately plugin does not support the latest versions of the IntelliJ IDE.

**Comment by Deadleg** [comment]
Version? Works for me on linux (2016.1.3/145.1617).

**Comment by splitice** [comment]
Ah sorry, I assumed based on the error message. Its actually too upgraded. 143.\* is the latest platform published with PHPStorm.

**Comment by Deadleg** [comment]
Fixed in 0.0.3. The idea gradle plugin was overwriting the build range to be the latest (145.+). Commit 335e383b20c53fbd934202d380fd5edfbc472bbd.
